### ISSUE TITLE
Upgrade to Rubocop 1.0

### ISSUE THREAD

**Issue by quartzmo** [googleapis/ruby-style#25]
https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#100-2020-10-21

**Comment by dazuma** [comment]
The Ruby 2.4 version (1.24) pins to a Rubocop release that happened before they started disabling new checks by default (i.e. during the time when minor releases were breaking). So we shouldn't update 1.24, but we should definitely use Rubocop 1.0 for 1.25.

**Comment by dazuma** [comment]
Done
