### ISSUE TITLE
Separate google-style-rspec gem

### ISSUE THREAD

**Issue by blowmage** [googleapis/ruby-style#4]
I would like to see this project follow the pattern established by the rubocop and rubocop-rspec gems and have a separate google-style-rspec gem. Projects that use the google-style gem but don't use Rspec shouldn't be required to install those dependencies, even as development dependencies.

**Comment by quartzmo** [comment]
@blowmage Specifically, for this project, you want [this line removed](https://github.com/googleapis/ruby-style/blob/master/google-style.gemspec#L31), correct?

**Comment by quartzmo** [comment]
I agree with this issue.

**Comment by blowmage** [comment]
Yes, I would remove that line. And I would move all files into a google-style directory and add an empty google-style-rspec directory. Basically, convert this into a monorepo.

**Comment by blowmage** [comment]
Closing due to monorepo prejudice.
